apiVersion: v1
kind: Secret
metadata:
  name: {{ include "artemis-helm.fullname" . }}
  labels:
{{ include "artemis-helm.labels.standard" . | indent 4 }}
type: Opaque
data:
  {{ if .Values.artemisPassword }}
  artemis-password:  {{ .Values.artemisPassword | b64enc | quote }}
  {{ else }}
  artemis-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{ end }}
