apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "artemis-helm.fullname" . }}-master
  annotations:
{{ toYaml .Values.deployment.annotations | indent 4 }}
  labels:
{{ include "artemis-helm.labels.standard" . | indent 4 }}
spec:
  serviceName: {{ include "artemis-helm.fullname" . }}-master
  replicas: {{ .Values.replicas }}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: {{ template "artemis-helm.name" . }}
      release: {{ .Release.Name | quote }}
      component: master
  template:
    metadata:
      name: {{ include "artemis-helm.fullname" . }}
      annotations:
{{ toYaml .Values.replica.annotations | indent 8 }}
      labels:
        app: {{ template "artemis-helm.name" . }}
        release: {{ .Release.Name | quote }}
        component: master
    spec:
      affinity:
        podAntiAffinity:
        {{- if eq .Values.antiAffinity "hard" }}
          requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: "kubernetes.io/hostname"
            labelSelector:
              matchLabels:
                app: {{ template "artemis-helm.name" . }}
                release: {{ .Release.Name | quote }}
                component: slave
        {{- else if eq .Values.antiAffinity "soft" }}
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 5
            podAffinityTerm:
              topologyKey: "kubernetes.io/hostname"
              labelSelector:
                matchLabels:
                  app: {{ template "artemis.name" . }}
                  release: {{ .Release.Name | quote }}
                  component: slave
        {{- end }}
      strategy:
        type: Recreate
      initContainers:
      - name: configure-cluster
        image: {{ template "artemis-helm.image" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        imagePullSecrets: {{ toYaml .Values.image.pullSecrets }}
      containers:
      - name: {{ include "artemis-helm.fullname" . }}
        image: {{ template "artemis-helm.image" . }}
        imagePullPolicy: {{ .Values.image.imagePullPolicy | quote }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
        env:
        - name: ARTEMIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "artemis-helm.fullname" . }}
              key: artemis-password
        - name: ARTEMIS_USERNAME
          value: {{ default "artemis" .Values.artemisUser | quote }}
        ports:
        - name: http
          containerPort: 8161
        - name: core
          containerPort: 61616
        - name: amqp
          containerPort: 5672
        livenessProbe:
          tcpSocket:
            port: http
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: core
          initialDelaySeconds: 10
          periodSeconds: 10
        volumeMounts:
        - name: data
          mountPath: /var/lib/artemis/data
        - name: config-override
          mountPath: /var/lib/artemis/etc-override
      volumes:
      - name: config-override
        emptyDir: {}
      - name: data
        emptyDir: {}
